gitonomy/gitlib

src/Gitonomy/Git/Exception/ProcessException.php
I tried to run the commit command without having properly adding the files to git and I got no output telling me what the problem was. I had to manually add this lines to see the error that came from git.
What do you think?
=> Adding process output to the exception description

src/Gitonomy/Git/Repository.php
No code changes; just a phpdoc comment change.
=> Fix phpdoc typehint on Repository->getHeadCommit()

src/Gitonomy/Git/Parser/LogParser.php, src/Gitonomy/Git/Parser/ParserBase.php, tests/Gitonomy/Git/Tests/AbstractTest.php, tests/Gitonomy/Git/Tests/PushReferenceTest.php
If commits are [signed gpg](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work) they will break the parsing of the log message since it's expecting two newlines after the commiter date where in the case of a GPG signature is added:
Example commit:
```
commit e1a83f16ed61ae3807e5652c7ef894692c813513
tree 90908bdccbb0b9c42fdb6225d5aa47d7c66c3d22
parent 583811146f79f1bf6e167d54b276e21553512d1a
author Stig Lindqvist <stojg.lindqvist@gmail.com> 1461274840 +1200
committer Stig Lindqvist <stojg.lindqvist@gmail.com> 1461274840 +1200
gpgsig -----BEGIN PGP SIGNATURE-----
Version: GnuPG v1
iQEcBAABAgAGBQJXGUjZAAoJEF7kfUZDyWQIaUkIAMYsSKA2C3XOQ2x0Ig3zOF5Y
DV1YlSWa2ILy/V49U55CWMP/Atbr1bKpREMI9y1T9tBwsMV1gtqYk+JwqyCntTjD
iaFexti++AZv47YrQa4aBtW18hRJp/BFrLjhkGnydHLvK1QJ2EAhIuqwRYiMHS8m …
```
=> Fix GPG signed commits breaks parsing of commit messages

src/Gitonomy/Git/Parser/CommitParser.php, tests/Gitonomy/Git/Tests/CommitTest.php
Ensure that we can get the full message when the commit has been GPG signed
Follow up on https://github.com/gitonomy/gitlib/pull/109 that only deals with the "log" part, this ensure that we can also return the message.
=> Fix GPG signed commits will break on reading full commit message

src/Gitonomy/Git/Repository.php
When initializing a `Repository` instance, if the specified directory doesn't exist, the `realpath` call with return `false` and overwrite the old value, which prevents it from being displayed in the exception. This does the trick.
Also, I added PHPUnit as a development dependency and wrote a quick *how-to* to run tests.
=> Better directory existence check to avoid empty paths in exception

composer.json
as for now, we don't know is software compatible with PHP 5.x or 7.x, we are just guessing.
I took 5.3+, as it's lowest job on Travis
=> Specify PHP requirement

src/Gitonomy/Git/Reference.php, src/Gitonomy/Git/ReferenceBag.php
[Phan](/phan/phan) rightfully complained about qualified class names which should have been fully qualified class names
=> Fix return types in docblocks

src/Gitonomy/Git/Parser/LogParser.php
There was an issue with LogParser unable to parse Git log when there is a commit with no message. The following exception would be thrown.
```
An uncaught Exception was encountered
Type: Gitonomy\Git\Exception\RuntimeException
Message: Expected " ", but got "c" (commit 896)
Filename: C:\Apache24\htdocs\apps\vendor\gitonomy\gitlib\src\Gitonomy\Git\Parser\ParserBase.php
Line Number: 111
Backtrace:
File: C:\Apache24\htdocs\apps\vendor\gitonomy\gitlib\src\Gitonomy\Git\Parser\ParserBase.php
Line: 120
Function: consume
File: C:\Apache24\htdocs\apps\vendor\gitonomy\gitlib\src\Gitonomy\Git\Parser\LogParser.php
Line: 60
Function: consumeNewLine
File: C:\Apache24\htdocs\apps\vendor\gitonomy\gitlib\src\Gitonomy\Git\Parser\ParserBase.php
Line: 30
Function: doParse
File: …
```
=> Fixed issue with LogParser unable to parse commit with no message

src/Gitonomy/Git/ReferenceBag.php
References for git time metrics (GTM)
```
[notes]
rewriteref = refs/notes/gtm-data
```
results with Fatal error:
```
Uncaught Gitonomy\Git\Exception\RuntimeException:
Unable to parse "refs/notes/gtm-data" in
/vendor/gitonomy/gitlib/src/Gitonomy/Git/ReferenceBag.php
on line 371
```
=> Add "refs/notes/gtm-data"

src/Gitonomy/Git/Parser/TagParser.php, src/Gitonomy/Git/Reference/Tag.php, tests/Gitonomy/Git/Tests/AbstractTest.php, tests/Gitonomy/Git/Tests/ReferenceTest.php
Similar to `Commit` and `CommitParser` to extract data from annotated tags.
Unit testing is available, but since it needs a properly annotated tag, `AbstractTest` is now pointing to my fork of `foobar` repo.
To add the same tag to the original repo:
``` bash
git config user.name "Bob"
git config user.email "bob@example.org"
GIT_COMMITTER_DATE="2016-08-17 12:00 +02:00" git tag -a annotated -m "heading
body
body"
```
=> Data in annotated tags

phpunit.xml.dist, tests/Gitonomy/Git/Tests/AdminTest.php, tests/Gitonomy/Git/Tests/CommitTest.php, tests/Gitonomy/Git/Tests/DiffTest.php, tests/Gitonomy/Git/Tests/HooksTest.php, tests/Gitonomy/Git/Tests/LogTest.php, tests/Gitonomy/Git/Tests/PushReferenceTest.php, tests/Gitonomy/Git/Tests/ReferenceTest.php, tests/Gitonomy/Git/Tests/RepositoryTest.php, tests/Gitonomy/Git/Tests/RevisionTest.php, tests/Gitonomy/Git/Tests/TreeTest.php, tests/Gitonomy/Git/Tests/WorkingCopyTest.php
- Using the `suffix` attribute defined on `phpunit.xml.dist` to mark test classes.
- According to the [PHPUnit fixtures reference](https://phpunit.de/manual/6.5/en/fixtures.html), the `setUp` method and `tearDown` method are `protected`, not `public`.
- Using the `assertInstanceOf` to assert expected class instance is same as `$actual`.
- Using the `assertCount` to assert the expected count value is same as `$actual` count value.
- Using the `assertDirectoryExists` to assert the specific directory is existed.
- Using the `assertContains` to assert the expected value contains on specific array.
- Using the `assertNotEmpty` to assert the specific value is set.
=> Test enhancement

tests/Gitonomy/Git/Tests/AdminTest.php, tests/Gitonomy/Git/Tests/BlobTest.php, tests/Gitonomy/Git/Tests/CommitTest.php, tests/Gitonomy/Git/Tests/HooksTest.php, tests/Gitonomy/Git/Tests/ReferenceTest.php, tests/Gitonomy/Git/Tests/RepositoryTest.php, tests/Gitonomy/Git/Tests/RevisionTest.php, tests/Gitonomy/Git/Tests/WorkingCopyTest.php
- To support future `PHPUnit 8.x` versions about deprecated `@expectedException` warning message, using the `expectException` and `expectExceptionMessage` instead.
- Removing unused variables.
The deprecated warning message is as follows:
```
with data set "empty string" ('')
The @expectedException, @expectedExceptionCode, @expectedExceptionMessage, and @expectedExceptionMessageRegExp annotations are deprecated. They will be removed in PHPUnit 9. Refactor your test to use expectException(), expectExceptionCode(), expectExceptionMessage(), or expectExceptionMessageRegExp() instead.
```
The related issue is available [here](https://github.com/sebastianbergmann/phpunit/issues/3332).
=> Enhance exception tests

src/Gitonomy/Git/ReferenceBag.php, tests/Gitonomy/Git/Tests/ReferenceBagTest.php
=> Ignore unknown refs instead of throwing an exception

src/Gitonomy/Git/Reference/Tag.php, tests/Gitonomy/Git/Tests/ReferenceTest.php
=> Get real commit for annotated tag

src/Gitonomy/Git/Repository.php, tests/Gitonomy/Git/Tests/RepositoryTest.php
This is the PHP implementation only version of Repository::getSize.
There are a couple of interesting things I discovered while doing this PR.
- Apparently the tests run twice, The second time the repository is bigger.
- The DU command measures in increments of 1000, not 1024, which is also a valid measurement for K in computers.  You say tomato, I say ...
So in the first run of the test, the size of the repo comes in just over 69,000 bytes, as measured by PHP and filesize.  On the second run of the test, it comes in at over 70,000 bytes.  So I changed the test to >= 69.
The second thing I did was put in a max size test, since that may detect a bug where you don't correctly divide by 1000. Don't ask how I know this.
So there is now an upper limit test of 80K, which should be OK for a …
=> Php only Repository::getsize

src/Gitonomy/Git/Repository.php
This is useful to refresh branch information like commit hash, after running git pull with `$repository->run('pull');` (like suggested in https://github.com/gitonomy/gitlib/issues/163)
=> Allow reload references from filesystem

src/Gitonomy/Git/Parser/DiffParser.php
Found this on my website where I access git commits as a diff. [PHPFUI/Instadoc](http://phpfui.com/?n=Gitonomy%5CGit%5CParser&c=DiffParser&p=g#) click on the top two commits to see the error in the wild. Will be fixed automatically when this PR is published. Site updates nightly.
This is just an 8.1 issue.
There may be other places this happens, but I have only run into this one.
=> Don't pass null as second parameter to preg_match

src/Gitonomy/Git/Parser/DiffParser.php
Sorry about this guys. My PHP 8.1 fix for not passing null was derailed by PHP 5.6 backport. I forgot to assign the value! AARRG!! I could have just put the expression into the function call directly, but I tend to do it outside, as I think it makes the code a little less complex and easier to read.
Again, my apologies.
=> Assign to variable to prevent null value

src/Gitonomy/Git/Blob.php, tests/Gitonomy/Git/Tests/BlobTest.php
First wanted to implement this through the use of `git ls-files --eol` but this would require you to know the tree, which is not always known.
[This comment](https://stackoverflow.com/a/6134127) on stack overflow pointed to the implementation git uses:
https://git.kernel.org/pub/scm/git/git.git/tree/xdiff-interface.c?h=v2.30.0#n187 
[latest version](https://git.kernel.org/pub/scm/git/git.git/tree/xdiff-interface.c?h=v2.40.1#n192) is unchanged
Closes #218
=> Detect binary file by NULL byte

tests/Gitonomy/Git/Tests/RepositoryTest.php
When cloning a project with git 2.43.2 some more files are added that increase the size of the repository, invalidating the size test.
on such file is a `pack-*.rev file` added in 2.41.0 https://github.blog/2023-06-01-highlights-from-git-2-41/#on-disk-reverse-indexes-by-default
Another one is `sendemail-validate.sample`, but could not quickly find in what version it was introduced.
There have also been some other  updates to files to make them larger.
In total the difference between git version 2.40.1 and 2.43.2 is 4028 bytes.
I have updated the tests to increase the size by 4 kb, also for the minimum size as with new git versions it does not seems to be close to this number.
Size diff:
```diff
@@ -1,7 +1,8 @@
-git version 2.40.1
+git version 2.43.2 …
```
=> Update tests for new git version

src/Gitonomy/Git/Parser/LogParser.php, tests/Gitonomy/Git/Tests/LogTest.php
Fixes #216 
Don't try to consume a 2nd new line when the first repository commit has an empty message.
=> Edge case: Empty message in the first commit

src/Gitonomy/Git/Commit.php, src/Gitonomy/Git/Parser/CommitParser.php, src/Gitonomy/Git/Parser/LogParser.php, src/Gitonomy/Git/Parser/TagParser.php, src/Gitonomy/Git/Reference/Tag.php, src/Gitonomy/Git/ReferenceBag.php
In `Commit.php` and `Tag.php` the computed value is stored in the class variable `$data` but in a (non existing) local `$data` variable. Causing recompute when the function is called again.
In `CommitParser.php`, `LogParser.php` and `TagParser.php` a function is called to get the date as a string and assigned to the class variable, only to be parsed as a `\DateTime` a line later and assigned to the same variable.
Solution used here to to create a temporary variable and parse that as a sate to avoid the class variable being two types.
In `ReferenceBag.php` the `initialize` has an try around run and the catch expect functions to be available on `RuntimeException` that where removed and just return null.
This seems to be behavior that is now expected. So if it throws an error a null is used …
=> Multiple small fixes

src/Gitonomy/Git/Parser/DiffParser.php, tests/Gitonomy/Git/Tests/DiffTest.php
The diff parser incorrectly parsed the below two diff patches
New file:
```diff
diff --git a/test b/test
new file mode 100644
index 0000000000000000000000000000000000000000..e69de29bb2d1d6434b8b29ae775ad8c2e48c5391
```
Deleted file:
```diff
diff --git a/test b/test
deleted file mode 100644
index e69de29bb2d1d6434b8b29ae775ad8c2e48c5391..0000000000000000000000000000000000000000
```
As the diff file would incorrectly leave the newName/oldName in the diff fille. Breaking the `isCreation()`, `isDeletion()` and related functions as it would still contain a file name.
This PR fixes this by setting the file name to `/dev/null` when it is a new/deleted file.
=> Fix incorrect file name on new or deleted empty files

src/Gitonomy/Git/Parser/LogParser.php, tests/Gitonomy/Git/Tests/LogTest.php
We have a problem with some repositories when trying to parse the commit logs of the repository.
Apparently, come of the committers, are using third party tools (https://gitbutler.com/) which tampers with the log and adds additional metadata that might or might not exist before the commit message (might not = not committed with gitbutler).
I have added a method to skip lines until a new line is found in order to accommodate for this.
I have also provided a test (hashes and names are random but it is part of the logs we have encountered) that proves the problem.
=> Skip third party unsupported headers.
